name: Python package

on:
  push:
    branches: '**' #[ $default-branch ]
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
#        python-version: ["3.3.7", "3.4.10", "3.5.10"]

    steps:
    - uses: actions/checkout@v4
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8, tox
    - name: Run tests and flake8 with tox
      run: |
        tox
